//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RojgarMitraEntities : DbContext
    {
        public RojgarMitraEntities()
            : base("name=RojgarMitraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<CountriesMaster> CountriesMasters { get; set; }
        public virtual DbSet<DesigationMaster> DesigationMasters { get; set; }
        public virtual DbSet<OtherMaster> OtherMasters { get; set; }
        public virtual DbSet<StatesMaster> StatesMasters { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<University_CollegeMaster> University_CollegeMaster { get; set; }
        public virtual DbSet<UserEducationDetail> UserEducationDetails { get; set; }
        public virtual DbSet<UserEmployementDetail> UserEmployementDetails { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserPreEmployeementDetail> UserPreEmployeementDetails { get; set; }
        public virtual DbSet<UserSkillsDetail> UserSkillsDetails { get; set; }
        public virtual DbSet<UserWokingHistory> UserWokingHistories { get; set; }
    }
}
