//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherMaster
    {
        public int MasterID { get; set; }
        public string Name { get; set; }
        public string CODE { get; set; }
        public string MasterType { get; set; }
        public bool IsActive { get; set; }
    }
}
