//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatesMaster
    {
        public long StateID { get; set; }
        public long CountryID { get; set; }
        public string Statename { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CountriesMaster CountriesMaster { get; set; }
    }
}
