//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_CollegeMaster
    {
        public long ID { get; set; }
        public string University_CollegeName { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
    }
}
