//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmployementDetail
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<int> CurrentDesignation { get; set; }
        public Nullable<int> CurrentCompany { get; set; }
        public string AnualSalaryType { get; set; }
        public string AnnualSalaryInlakhs { get; set; }
        public Nullable<int> AnnualSalaryInThousand { get; set; }
        public Nullable<int> WorkingSinceYear { get; set; }
        public string WotkingSinceMonth { get; set; }
        public string WorkingTo { get; set; }
        public Nullable<int> CurrentLocationID { get; set; }
        public string CityName { get; set; }
        public Nullable<bool> OutSideIndia { get; set; }
        public Nullable<int> OutSideIndiaCountryID { get; set; }
        public string OutSideIndiaCity { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<bool> ServeNoticePeriod { get; set; }
        public Nullable<int> LastWorkingDay_Year { get; set; }
        public Nullable<int> Last_Working_Month { get; set; }
        public Nullable<int> Last_WorkingDate { get; set; }
        public string NewOfferedSalaryIn { get; set; }
        public Nullable<int> NewOfferedSalaryInLakh { get; set; }
        public Nullable<int> NewOfferedSalaryInThousand { get; set; }
        public Nullable<int> OfferedDesignation { get; set; }
        public Nullable<int> NewCompany { get; set; }
        public Nullable<int> PassingYear { get; set; }
        public Nullable<int> FunctionalAreaID { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public string JobType { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
