//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWokingHistory
    {
        public long ID { get; set; }
        public long UserId { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<int> WokingSinceYear { get; set; }
        public Nullable<int> workingSinceMonth { get; set; }
        public Nullable<int> WorkingSinceTo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
