//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreEmployeementDetail
    {
        public long PreEmpID { get; set; }
        public long UserID { get; set; }
        public Nullable<int> Desigation { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Duration_FromYear { get; set; }
        public Nullable<int> Duration_FromMonth { get; set; }
        public Nullable<int> Duration_ToYear { get; set; }
        public string Duration_ToMonth { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
